#eureka:
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka
#  instance:
#    hostname: localhost

server:
  port: 9192
spring:
  application:
    name: VEHICLE-DETAILS-API
  datasource:
    username: springboot
    password: springboot
    url: jdbc:mysql://localhost:3306/vehicle
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  config:
    import: optional:configserver:http://localhost:9194
